### ISSUE TITLE
Deeplink is not working on Linux/Ubuntu

### ISSUE THREAD

**Issue by vijaygodhasara** [glawson/electron-deeplink#20]
Deeplink is not working on Linux/Ubuntu.

Installed and integrated plugin into our electron project.
open on chrome with :
<a href="myapp://param">Open app</a>

getting below error
![linux_deeplink_issue](https://user-images.githubusercontent.com/11735224/96600706-d7726380-130e-11eb-8b84-495e40fedda2.png)

**Comment by glawson** [comment]
@vijaygodhasara  I'm not sure if electron is even supporting this on Linux - the doc is not very clear.  Only mentions Windows and MacOS - https://www.electronjs.org/docs/api/app#appsetasdefaultprotocolclientprotocol-path-args

**Comment by glawson** [comment]
@vijaygodhasara - it should work on Linux, I'll debug it in the next couple of days.

**Comment by vijaygodhasara** [comment]
Thanks, Once done let me know so I can check also this stuff on Linux/ubuntu as well.

**Comment by glawson** [comment]
@vijaygodhasara - sorry it's taken so long.  I did find the error and will have a fix out soon (I expect tomorrow).

**Comment by cedriking** [comment]
> @vijaygodhasara - sorry it's taken so long. I did find the error and will have a fix out soon (I expect tomorrow).

Is this now solved? The issue is still marked as open and no replies after this one. Thanks.

**Comment by glawson** [comment]
@cedriking - unfortunately not.  There are some mixed issues regarding app.setAsDefaultProtocolClient on Linux.  I tested on Linux and was never able to get it working.  I also posted to the electron slack group, never got a response.  I'll dig deeper and respond back.

**Comment by yeefun** [comment]
I try this, and it works.
https://stackoverflow.com/a/66366790

The point is:
```yml
    desktop:                            # Define desktop elem
        exec: myapp %u                  # Define Exec
```

**Comment by glawson** [comment]
Thanks @yeefun - I'll see if we can incorporate.

**Comment by yeefun** [comment]
Sorry, I found it doesn't work in every Linux platform.

**Comment by glawson** [comment]
@yeefun - thanks for letting me know.

**Comment by Joelkang** [comment]
I think this is where the bug lies:
https://github.com/glawson/electron-deeplink/blob/de4690fde309c712996b871fc3ccff05d540eac1/src/index.ts#L145-L154

Because `open-url` and `open-file` are MacOS only, linux is missing the `emit('received')` call that windows has. What I wound up having to do to get around this was essentially re-implementing some parts of this library:
```ts
if (!gotTheLock) {
  app.quit();
} else {
  const onDeepLink = (link) => {...};
  app.on('second-instance', (_event: Event, args: string[]) => {
    if (['darwin','win32'].includes(process.platform)) return; // This is properly handled by electron-deep-link
    const [_executable, link] = args;
    onDeepLink(link);
  });
  ...
  deepLink = new Deeplink({
    app,
    mainWindow,
    protocol: 'myApp',
  });
  deepLink.on('received', onDeepLink);
}
```

As a side note, it feels a bit like a leaky abstraction to pass in the MainWindow at all--in particular, I have several windows that I show and hide based on whether the user is logged in (and what deep link is called). So it's not always the case that that the mainWindow should be open on a 2nd instance, or when a deeplink is called. Since callers already receive the `received` event (this bug not withstanding), they can call within that listener this portion if they wish to focus their main window:
```ts
if (this.mainWindow.isMinimized()) { 
    this.mainWindow.restore(); 
} 
this.mainWindow.focus(); 
```
That said, this is a breaking change, and not really related to this issue, so feel free to ignore.

@glawson  happy to throw up a PR to fix this if you'd like!

**Comment by glawson** [comment]
@Joelkang - that would be awesome!

**Comment by yeefun** [comment]
https://github.com/glawson/electron-deeplink/issues/20#issuecomment-947097956

@Joelkang - I wonder if you test it on Linux and it works?

**Comment by Joelkang** [comment]
@yeefun yep, I did. In addition to the changes I made above, I had to make this additional change to my Electron Forge config:

```js
 {
      name: '@electron-forge/maker-deb',
      config: {
        options: {
          // existing options ...
          mimeType: ['x-scheme-handler/myApp'], // I added this
        },
      },
    },

```

**Comment by yeefun** [comment]
@Joelkang - I also did this, but it didn't work in every Linux platform. (BTW, I use electron-builder.)

what your Desktop Entry looks like?

**Comment by Joelkang** [comment]
@glawson: Whenever you're ready! (Woops sorry should've checked first before forcepushing so many times.)

@yeefun unfortunately I'm not trying to fix this for *all* linuxes--as long as it works on ubuntu, i'm good (though it doesn't seem like it shouldn't work on any other flavour).

Here's the desktop file generated from electron-forge:
```
Name=Dala
Comment=Dala description
GenericName=Dala
Exec=dala %U
Icon=dala
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;
MimeType=x-scheme-handler/dala;
```
