### ISSUE TITLE
install failed in mac silicon 

### ISSUE THREAD

**Issue by leeleoo** [glawson/electron-deeplink#38]
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/9399623/166931483-1a0470be-4305-46c1-9fd7-d6ee95b53a3f.png">

**Comment by leeleoo** [comment]
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/9399623/166953929-5568ac5c-b2d0-4649-9a5f-75100b5f764b.png">

**Comment by glawson** [comment]
thanks @leeleoo.  Looks like an issue with `incompatible architecture (have x86_64, need arm64e)`, which is from python3.   Seems that `node-gyp` needs to be updated.  Would you mind trying something for me?  Install node-gyp v9: `npm i -D node-gpy@9.0.0`.  Then add `{ "overrides": { "electron-deeplink": {"node-gyp": "^9.0.0" } } }` to your package.json then remove and reinstall electron-deeplink.  Please let me know the results.

**Comment by leeleoo** [comment]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/9399623/167051615-ebec0512-8ddd-47cb-8700-b3c9bc37a64f.png">
<img width="552" alt="image" src="https://user-images.githubusercontent.com/9399623/167051644-6f4deb47-09a6-46e5-8837-5968771afe5d.png">
@glawson  has the same error with this configuration

**Comment by glawson** [comment]
@leeleoo - thanks for checking.  I'll be looking into it.

**Comment by pirog** [comment]
@glawson @leeleoo FWIW i think this happens because node 14 ships only a `x86_64` binary which runs under emulation on M1 macs via Rosetta. The logs posted above indicates that eg node thinks its running on `x86_64`. Guessing `node` thinks its `x86_64` but `node-gyp` thinks its `arm64` and the mismatch is the issue.

If you install node 16, which is a universal binary, you can avoid the mismatch. for reference a universal binary is a "fat" binary with both `arm64` and `x86_64` binaries inside of it.

you can verify the arch node is detecting with `node -p process.arch`.

also @glawson this project is cool but im able to utilize a custom protocol eg `myapp://` when in dev mode and also in production just using electron and its apis. so im curious why you are including the `.mm` part? am i missing something? i see that the file is from 2 years ago so maybe these things just didnt exist in electron at the time?

regardless, it would be cool to be able to turn off the `node-gyp` part of this. other devs might choose to implement the system level protocol stuff differently but want to use the awesome handling logic you have in the `DeepLink` class. would you be open to any of that?

**Comment by glawson** [comment]
@pirog - thanks!  Yes, 2 years ago the protocol api wasn't completely working - https://github.com/glawson/electron-deeplink#electron-deeplink.  I ❤️ the idea of optionally turning off `node-gyp`, I will work that in soonish.

@leeleoo - please follow @pirog 's direction, install node 16.  Let us know.

**Comment by leeleoo** [comment]
@pirog Great ！ Your guess is perfect. I upgraded nodejs to 16 and solved this problem 

@glawson and thank you guys so much

**Comment by pirog** [comment]
HUZZAH!
